insert into Base (BaseID, BaseName, Location_) values ('716411', 'Wolfpack Camp', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('299961', 'Lion''s Den', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('021950', 'Thunderbolt Barracks', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('618595', 'Shadow Ridge Base', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('155077', 'Spartan Citadel', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('522468', 'Thunderbolt Barracks', 'Qiryat Ono');
insert into Base (BaseID, BaseName, Location_) values ('611132', 'Wolfpack Camp', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('656992', 'Phoenix Stronghold', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('755215', 'Wolfpack Camp', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('596693', 'Wolfpack Camp', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('647973', 'Spartan Citadel', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('286784', 'Thunderstrike Outpost', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('480786', 'Iron Fortress', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('238744', 'Shadow Ridge Base', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('267671', 'Lion''s Den', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('880598', 'Lion''s Den', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('741586', 'Lion''s Den', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('250479', 'Shadow Ridge Base', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('531268', 'Shadow Ridge Base', 'Beit She''an');
insert into Base (BaseID, BaseName, Location_) values ('713497', 'Shadow Ridge Base', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('865889', 'Wolfpack Camp', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('426820', 'Eagle''s Nest', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('442496', 'Viper Valley Base', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('615770', 'Eagle''s Nest', 'Hadera');
insert into Base (BaseID, BaseName, Location_) values ('895105', 'Phoenix Stronghold', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('899020', 'Thunderbolt Barracks', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('715708', 'Phoenix Stronghold', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('778941', 'Thunderbolt Barracks', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('633184', 'Shadow Ridge Base', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('551900', 'Eagle''s Nest', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('700167', 'Thunderstrike Outpost', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('446760', 'Wolfpack Camp', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('166454', 'Eagle''s Nest', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('661289', 'Shadow Ridge Base', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('455324', 'Thunderbolt Barracks', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('106290', 'Shadow Ridge Base', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('974212', 'Wolfpack Camp', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('911808', 'Thunderstrike Outpost', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('908103', 'Thunderbolt Barracks', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('100783', 'Thunderbolt Barracks', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('179934', 'Shadow Ridge Base', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('494318', 'Shadow Ridge Base', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('649718', 'Thunderbolt Barracks', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('927099', 'Shadow Ridge Base', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('976428', 'Phoenix Stronghold', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('880200', 'Thunderstrike Outpost', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('377741', 'Thunderstrike Outpost', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('722229', 'Wolfpack Camp', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('828472', 'Thunderstrike Outpost', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('551839', 'Iron Fortress', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('742032', 'Shadow Ridge Base', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('729081', 'Thunderbolt Barracks', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('034118', 'Wolfpack Camp', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('364577', 'Wolfpack Camp', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('046331', 'Wolfpack Camp', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('279354', 'Wolfpack Camp', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('942714', 'Phoenix Stronghold', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('834871', 'Shadow Ridge Base', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('047001', 'Eagle''s Nest', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('305781', 'Iron Fortress', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('816236', 'Eagle''s Nest', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('399684', 'Thunderbolt Barracks', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('390291', 'Viper Valley Base', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('748905', 'Iron Fortress', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('683294', 'Spartan Citadel', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('642912', 'Iron Fortress', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('705122', 'Thunderstrike Outpost', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('641207', 'Wolfpack Camp', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('963848', 'Shadow Ridge Base', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('442587', 'Lion''s Den', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('330582', 'Iron Fortress', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('144504', 'Thunderbolt Barracks', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('002245', 'Eagle''s Nest', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('897006', 'Phoenix Stronghold', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('489684', 'Thunderbolt Barracks', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('954472', 'Spartan Citadel', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('836092', 'Iron Fortress', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('869324', 'Viper Valley Base', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('588125', 'Phoenix Stronghold', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('816168', 'Thunderbolt Barracks', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('310136', 'Lion''s Den', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('683034', 'Viper Valley Base', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('869543', 'Iron Fortress', 'Kiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('929761', 'Iron Fortress', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('047886', 'Eagle''s Nest', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('597826', 'Thunderbolt Barracks', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('068630', 'Lion''s Den', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('620780', 'Thunderstrike Outpost', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('682213', 'Lion''s Den', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('932705', 'Phoenix Stronghold', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('263152', 'Lion''s Den', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('140152', 'Thunderbolt Barracks', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('151647', 'Eagle''s Nest', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('006019', 'Phoenix Stronghold', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('062060', 'Spartan Citadel', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('255941', 'Thunderbolt Barracks', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('332743', 'Thunderstrike Outpost', 'Yehud');
insert into Base (BaseID, BaseName, Location_) values ('408669', 'Thunderbolt Barracks', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('862885', 'Phoenix Stronghold', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('756586', 'Shadow Ridge Base', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('731509', 'Thunderbolt Barracks', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('496151', 'Thunderstrike Outpost', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('969453', 'Phoenix Stronghold', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('859404', 'Spartan Citadel', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('623056', 'Spartan Citadel', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('847122', 'Wolfpack Camp', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('734636', 'Spartan Citadel', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('092483', 'Spartan Citadel', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('319095', 'Viper Valley Base', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('273935', 'Viper Valley Base', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('265293', 'Thunderstrike Outpost', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('759136', 'Phoenix Stronghold', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('513500', 'Wolfpack Camp', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('216148', 'Wolfpack Camp', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('119855', 'Thunderstrike Outpost', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('368287', 'Iron Fortress', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('010248', 'Wolfpack Camp', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('120796', 'Wolfpack Camp', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('819635', 'Lion''s Den', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('023650', 'Iron Fortress', 'Qiryat Ono');
insert into Base (BaseID, BaseName, Location_) values ('951081', 'Thunderstrike Outpost', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('453395', 'Eagle''s Nest', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('484085', 'Wolfpack Camp', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('784195', 'Thunderstrike Outpost', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('587660', 'Viper Valley Base', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('324460', 'Viper Valley Base', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('001245', 'Phoenix Stronghold', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('148409', 'Thunderbolt Barracks', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('050069', 'Wolfpack Camp', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('721322', 'Thunderbolt Barracks', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('759740', 'Thunderstrike Outpost', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('337680', 'Shadow Ridge Base', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('518587', 'Spartan Citadel', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('650932', 'Wolfpack Camp', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('668822', 'Thunderstrike Outpost', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('188581', 'Eagle''s Nest', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('899114', 'Viper Valley Base', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('540629', 'Eagle''s Nest', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('868902', 'Iron Fortress', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('860013', 'Lion''s Den', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('701007', 'Thunderstrike Outpost', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('939397', 'Shadow Ridge Base', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('685117', 'Thunderstrike Outpost', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('668766', 'Thunderbolt Barracks', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('816153', 'Thunderbolt Barracks', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('866648', 'Thunderstrike Outpost', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('751870', 'Thunderbolt Barracks', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('342772', 'Thunderstrike Outpost', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('259781', 'Thunderbolt Barracks', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('227601', 'Wolfpack Camp', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('524939', 'Iron Fortress', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('160036', 'Thunderstrike Outpost', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('233108', 'Iron Fortress', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('788357', 'Iron Fortress', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('002655', 'Lion''s Den', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('240640', 'Thunderstrike Outpost', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('074836', 'Spartan Citadel', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('847911', 'Iron Fortress', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('047639', 'Phoenix Stronghold', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('679720', 'Spartan Citadel', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('023321', 'Eagle''s Nest', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('000336', 'Thunderstrike Outpost', 'Hadera');
insert into Base (BaseID, BaseName, Location_) values ('913158', 'Thunderstrike Outpost', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('876873', 'Iron Fortress', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('744868', 'Spartan Citadel', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('994218', 'Thunderbolt Barracks', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('476658', 'Eagle''s Nest', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('397261', 'Eagle''s Nest', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('077942', 'Thunderstrike Outpost', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('859250', 'Spartan Citadel', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('767293', 'Thunderbolt Barracks', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('890899', 'Wolfpack Camp', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('293957', 'Spartan Citadel', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('328059', 'Lion''s Den', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('699634', 'Thunderstrike Outpost', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('706400', 'Lion''s Den', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('345685', 'Spartan Citadel', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('647129', 'Eagle''s Nest', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('620115', 'Wolfpack Camp', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('379958', 'Viper Valley Base', 'Qiryat Ono');
insert into Base (BaseID, BaseName, Location_) values ('515315', 'Viper Valley Base', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('922330', 'Iron Fortress', 'Qiryat Ono');
insert into Base (BaseID, BaseName, Location_) values ('517793', 'Thunderbolt Barracks', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('549679', 'Shadow Ridge Base', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('954755', 'Wolfpack Camp', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('594710', 'Wolfpack Camp', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('751023', 'Iron Fortress', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('309315', 'Spartan Citadel', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('775716', 'Thunderbolt Barracks', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('480859', 'Shadow Ridge Base', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('758840', 'Iron Fortress', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('038609', 'Spartan Citadel', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('376878', 'Eagle''s Nest', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('864124', 'Wolfpack Camp', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('384216', 'Viper Valley Base', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('084493', 'Lion''s Den', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('796180', 'Thunderstrike Outpost', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('623967', 'Phoenix Stronghold', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('725691', 'Thunderbolt Barracks', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('248440', 'Iron Fortress', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('885066', 'Wolfpack Camp', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('514129', 'Spartan Citadel', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('530876', 'Thunderstrike Outpost', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('961068', 'Thunderbolt Barracks', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('098592', 'Spartan Citadel', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('038757', 'Thunderbolt Barracks', 'Hadera');
insert into Base (BaseID, BaseName, Location_) values ('047840', 'Phoenix Stronghold', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('602773', 'Shadow Ridge Base', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('336796', 'Eagle''s Nest', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('010979', 'Wolfpack Camp', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('349924', 'Thunderbolt Barracks', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('383721', 'Eagle''s Nest', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('465888', 'Phoenix Stronghold', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('775138', 'Thunderstrike Outpost', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('612393', 'Eagle''s Nest', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('659078', 'Thunderstrike Outpost', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('799516', 'Shadow Ridge Base', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('084788', 'Phoenix Stronghold', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('958966', 'Shadow Ridge Base', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('858128', 'Phoenix Stronghold', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('614465', 'Lion''s Den', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('221486', 'Eagle''s Nest', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('487915', 'Thunderstrike Outpost', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('205083', 'Thunderbolt Barracks', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('293141', 'Eagle''s Nest', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('877596', 'Thunderstrike Outpost', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('792649', 'Viper Valley Base', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('053537', 'Lion''s Den', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('073272', 'Thunderstrike Outpost', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('620389', 'Eagle''s Nest', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('050445', 'Wolfpack Camp', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('187898', 'Lion''s Den', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('413161', 'Eagle''s Nest', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('863003', 'Lion''s Den', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('452827', 'Thunderbolt Barracks', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('178961', 'Eagle''s Nest', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('292308', 'Eagle''s Nest', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('836206', 'Thunderstrike Outpost', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('587039', 'Viper Valley Base', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('076132', 'Shadow Ridge Base', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('231553', 'Shadow Ridge Base', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('884030', 'Shadow Ridge Base', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('438314', 'Thunderstrike Outpost', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('447667', 'Eagle''s Nest', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('146017', 'Iron Fortress', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('989717', 'Shadow Ridge Base', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('433046', 'Thunderbolt Barracks', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('569207', 'Eagle''s Nest', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('499295', 'Viper Valley Base', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('874803', 'Thunderstrike Outpost', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('756998', 'Shadow Ridge Base', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('319961', 'Iron Fortress', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('678476', 'Shadow Ridge Base', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('959379', 'Wolfpack Camp', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('568920', 'Iron Fortress', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('858401', 'Iron Fortress', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('968173', 'Lion''s Den', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('614710', 'Spartan Citadel', 'Hadera');
insert into Base (BaseID, BaseName, Location_) values ('791323', 'Thunderstrike Outpost', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('989781', 'Thunderstrike Outpost', 'Yehud');
insert into Base (BaseID, BaseName, Location_) values ('353864', 'Viper Valley Base', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('674598', 'Eagle''s Nest', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('977819', 'Viper Valley Base', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('846475', 'Thunderstrike Outpost', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('827285', 'Spartan Citadel', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('455430', 'Shadow Ridge Base', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('340647', 'Lion''s Den', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('033375', 'Viper Valley Base', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('927868', 'Spartan Citadel', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('227870', 'Thunderstrike Outpost', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('144218', 'Eagle''s Nest', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('475096', 'Iron Fortress', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('532513', 'Wolfpack Camp', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('403608', 'Wolfpack Camp', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('361210', 'Shadow Ridge Base', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('480466', 'Viper Valley Base', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('017709', 'Thunderbolt Barracks', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('447820', 'Shadow Ridge Base', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('814409', 'Thunderstrike Outpost', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('728458', 'Phoenix Stronghold', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('203945', 'Eagle''s Nest', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('751293', 'Wolfpack Camp', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('743851', 'Viper Valley Base', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('846536', 'Thunderstrike Outpost', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('701603', 'Eagle''s Nest', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('273863', 'Wolfpack Camp', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('714309', 'Thunderstrike Outpost', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('931588', 'Lion''s Den', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('353648', 'Viper Valley Base', 'Kiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('352561', 'Phoenix Stronghold', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('530515', 'Eagle''s Nest', 'Negev Desert');
insert into Base (BaseID, BaseName, Location_) values ('449558', 'Lion''s Den', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('485586', 'Eagle''s Nest', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('488616', 'Eagle''s Nest', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('043092', 'Viper Valley Base', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('509396', 'Iron Fortress', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('402382', 'Lion''s Den', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('395961', 'Viper Valley Base', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('699803', 'Iron Fortress', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('786247', 'Wolfpack Camp', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('001615', 'Shadow Ridge Base', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('604306', 'Phoenix Stronghold', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('186088', 'Eagle''s Nest', 'Kiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('543705', 'Wolfpack Camp', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('573438', 'Eagle''s Nest', 'Bat Yam');
insert into Base (BaseID, BaseName, Location_) values ('345659', 'Spartan Citadel', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('407361', 'Thunderbolt Barracks', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('709185', 'Wolfpack Camp', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('357321', 'Phoenix Stronghold', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('040654', 'Phoenix Stronghold', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('528153', 'Viper Valley Base', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('469677', 'Eagle''s Nest', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('108645', 'Viper Valley Base', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('281045', 'Iron Fortress', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('774812', 'Thunderbolt Barracks', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('584448', 'Iron Fortress', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('710007', 'Phoenix Stronghold', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('666126', 'Viper Valley Base', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('240754', 'Eagle''s Nest', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('773846', 'Spartan Citadel', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('671613', 'Wolfpack Camp', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('200059', 'Viper Valley Base', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('888325', 'Shadow Ridge Base', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('146757', 'Thunderstrike Outpost', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('682789', 'Thunderbolt Barracks', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('973763', 'Shadow Ridge Base', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('554496', 'Phoenix Stronghold', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('344138', 'Eagle''s Nest', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('535678', 'Thunderbolt Barracks', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('118229', 'Iron Fortress', 'Beit She''an');
insert into Base (BaseID, BaseName, Location_) values ('082511', 'Iron Fortress', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('784254', 'Eagle''s Nest', 'Netanya');
insert into Base (BaseID, BaseName, Location_) values ('191406', 'Shadow Ridge Base', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('965900', 'Phoenix Stronghold', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('439580', 'Thunderbolt Barracks', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('275277', 'Viper Valley Base', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('860827', 'Iron Fortress', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('151706', 'Eagle''s Nest', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('750472', 'Lion''s Den', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('083008', 'Lion''s Den', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('815890', 'Iron Fortress', 'Yehud');
insert into Base (BaseID, BaseName, Location_) values ('972135', 'Lion''s Den', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('041866', 'Shadow Ridge Base', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('688633', 'Wolfpack Camp', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('680356', 'Thunderbolt Barracks', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('957716', 'Viper Valley Base', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('749779', 'Spartan Citadel', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('891761', 'Phoenix Stronghold', 'Dead Sea');
insert into Base (BaseID, BaseName, Location_) values ('154392', 'Phoenix Stronghold', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('646127', 'Phoenix Stronghold', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('375123', 'Spartan Citadel', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('931041', 'Viper Valley Base', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('377985', 'Lion''s Den', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('363757', 'Phoenix Stronghold', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('876383', 'Wolfpack Camp', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('062223', 'Shadow Ridge Base', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('033710', 'Iron Fortress', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('490738', 'Phoenix Stronghold', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('985349', 'Spartan Citadel', 'Beit She''an');
insert into Base (BaseID, BaseName, Location_) values ('964343', 'Shadow Ridge Base', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('858069', 'Wolfpack Camp', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('675567', 'Thunderstrike Outpost', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('754671', 'Eagle''s Nest', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('914132', 'Iron Fortress', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('463085', 'Wolfpack Camp', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('623670', 'Iron Fortress', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('902274', 'Lion''s Den', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('999177', 'Thunderbolt Barracks', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('642815', 'Thunderstrike Outpost', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('221094', 'Iron Fortress', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('611059', 'Thunderstrike Outpost', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('860364', 'Spartan Citadel', 'Ramat Hasharon');
insert into Base (BaseID, BaseName, Location_) values ('359188', 'Wolfpack Camp', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('688663', 'Phoenix Stronghold', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('124184', 'Spartan Citadel', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('692776', 'Iron Fortress', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('939572', 'Shadow Ridge Base', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('756864', 'Thunderbolt Barracks', 'Yehud');
insert into Base (BaseID, BaseName, Location_) values ('266734', 'Lion''s Den', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('537740', 'Phoenix Stronghold', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('633859', 'Viper Valley Base', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('546581', 'Phoenix Stronghold', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('056401', 'Iron Fortress', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('454026', 'Phoenix Stronghold', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('531798', 'Thunderstrike Outpost', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('304359', 'Spartan Citadel', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('345748', 'Thunderstrike Outpost', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('202720', 'Lion''s Den', 'Kiryat Malachi');
insert into Base (BaseID, BaseName, Location_) values ('779320', 'Thunderstrike Outpost', 'Beit She''an');
insert into Base (BaseID, BaseName, Location_) values ('881261', 'Phoenix Stronghold', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('672678', 'Shadow Ridge Base', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('386597', 'Eagle''s Nest', 'Holon');
insert into Base (BaseID, BaseName, Location_) values ('962591', 'Spartan Citadel', 'Beit She''an');
insert into Base (BaseID, BaseName, Location_) values ('106764', 'Thunderstrike Outpost', 'Yehud');
insert into Base (BaseID, BaseName, Location_) values ('249816', 'Eagle''s Nest', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('629041', 'Viper Valley Base', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('719061', 'Thunderbolt Barracks', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('160633', 'Viper Valley Base', 'Jaffa');
insert into Base (BaseID, BaseName, Location_) values ('624230', 'Lion''s Den', 'Ra''anana');
insert into Base (BaseID, BaseName, Location_) values ('502795', 'Lion''s Den', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('962423', 'Spartan Citadel', 'Kiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('503871', 'Thunderbolt Barracks', 'Rosh HaAyin');
insert into Base (BaseID, BaseName, Location_) values ('325138', 'Shadow Ridge Base', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('649739', 'Spartan Citadel', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('281344', 'Wolfpack Camp', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('450193', 'Viper Valley Base', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('017547', 'Eagle''s Nest', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('725850', 'Thunderbolt Barracks', 'Qiryat Shemona');
insert into Base (BaseID, BaseName, Location_) values ('000731', 'Iron Fortress', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('476517', 'Phoenix Stronghold', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('728389', 'Shadow Ridge Base', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('525734', 'Lion''s Den', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('734284', 'Wolfpack Camp', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('657775', 'Thunderstrike Outpost', 'Nesher');
insert into Base (BaseID, BaseName, Location_) values ('445026', 'Thunderbolt Barracks', 'Hadera');
insert into Base (BaseID, BaseName, Location_) values ('049918', 'Wolfpack Camp', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('501100', 'Thunderbolt Barracks', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('010798', 'Thunderbolt Barracks', 'Yehud');
insert into Base (BaseID, BaseName, Location_) values ('662779', 'Viper Valley Base', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('760245', 'Thunderbolt Barracks', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('240523', 'Eagle''s Nest', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('842106', 'Thunderbolt Barracks', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('818365', 'Shadow Ridge Base', 'Hadera');
insert into Base (BaseID, BaseName, Location_) values ('964050', 'Wolfpack Camp', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('094161', 'Thunderstrike Outpost', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('354922', 'Thunderstrike Outpost', 'Safed');
insert into Base (BaseID, BaseName, Location_) values ('760471', 'Thunderstrike Outpost', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('140504', 'Viper Valley Base', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('277631', 'Lion''s Den', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('937314', 'Spartan Citadel', 'Ashkelon');
insert into Base (BaseID, BaseName, Location_) values ('856459', 'Shadow Ridge Base', 'Herzliya');
insert into Base (BaseID, BaseName, Location_) values ('856492', 'Thunderbolt Barracks', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('342517', 'Iron Fortress', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('466247', 'Viper Valley Base', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('807194', 'Shadow Ridge Base', 'Galilee');
insert into Base (BaseID, BaseName, Location_) values ('586970', 'Shadow Ridge Base', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('007739', 'Eagle''s Nest', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('629855', 'Viper Valley Base', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('498703', 'Viper Valley Base', 'Tzfat');
insert into Base (BaseID, BaseName, Location_) values ('104527', 'Spartan Citadel', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('878311', 'Lion''s Den', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('426031', 'Eagle''s Nest', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('661884', 'Spartan Citadel', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('826560', 'Phoenix Stronghold', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('554828', 'Thunderstrike Outpost', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('756250', 'Lion''s Den', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('308227', 'Iron Fortress', 'Qiryat Ono');
insert into Base (BaseID, BaseName, Location_) values ('658283', 'Shadow Ridge Base', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('491038', 'Wolfpack Camp', 'Nazareth');
insert into Base (BaseID, BaseName, Location_) values ('410059', 'Wolfpack Camp', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('018815', 'Spartan Citadel', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('000921', 'Shadow Ridge Base', 'Jerusalem');
insert into Base (BaseID, BaseName, Location_) values ('235479', 'Thunderstrike Outpost', 'Beit She''an');
insert into Base (BaseID, BaseName, Location_) values ('148881', 'Iron Fortress', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('611403', 'Phoenix Stronghold', 'Arad');
insert into Base (BaseID, BaseName, Location_) values ('108158', 'Thunderbolt Barracks', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('772783', 'Shadow Ridge Base', 'Rishon LeZion');
insert into Base (BaseID, BaseName, Location_) values ('212492', 'Iron Fortress', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('399673', 'Spartan Citadel', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('770115', 'Shadow Ridge Base', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('697926', 'Phoenix Stronghold', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('844289', 'Spartan Citadel', 'Acre');
insert into Base (BaseID, BaseName, Location_) values ('545434', 'Lion''s Den', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('045743', 'Spartan Citadel', 'Qiryat Ono');
insert into Base (BaseID, BaseName, Location_) values ('646102', 'Thunderbolt Barracks', 'Ramat Gan');
insert into Base (BaseID, BaseName, Location_) values ('194232', 'Shadow Ridge Base', 'Sderot');
insert into Base (BaseID, BaseName, Location_) values ('750009', 'Phoenix Stronghold', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('925844', 'Shadow Ridge Base', 'Tel Aviv');
insert into Base (BaseID, BaseName, Location_) values ('851112', 'Eagle''s Nest', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('799217', 'Phoenix Stronghold', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('574000', 'Lion''s Den', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('596050', 'Eagle''s Nest', 'Ma''alot-Tarshiha');
insert into Base (BaseID, BaseName, Location_) values ('122194', 'Spartan Citadel', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('941754', 'Thunderstrike Outpost', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('577366', 'Thunderstrike Outpost', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('974391', 'Lion''s Den', 'Lod');
insert into Base (BaseID, BaseName, Location_) values ('930274', 'Lion''s Den', 'Modi''in');
insert into Base (BaseID, BaseName, Location_) values ('312520', 'Thunderbolt Barracks', 'Caesarea');
insert into Base (BaseID, BaseName, Location_) values ('372564', 'Spartan Citadel', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('487884', 'Shadow Ridge Base', 'Qiryat Bialik');
insert into Base (BaseID, BaseName, Location_) values ('693404', 'Iron Fortress', 'Qiryat Yam');
insert into Base (BaseID, BaseName, Location_) values ('308304', 'Shadow Ridge Base', 'Qiryat Ata');
insert into Base (BaseID, BaseName, Location_) values ('179203', 'Spartan Citadel', 'Beer Sheva');
insert into Base (BaseID, BaseName, Location_) values ('171641', 'Iron Fortress', 'Kfar Saba');
insert into Base (BaseID, BaseName, Location_) values ('965241', 'Viper Valley Base', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('101552', 'Spartan Citadel', 'Qiryat Motzkin');
insert into Base (BaseID, BaseName, Location_) values ('889116', 'Thunderbolt Barracks', 'Tiberias');
insert into Base (BaseID, BaseName, Location_) values ('169180', 'Iron Fortress', 'Petah Tikva');
insert into Base (BaseID, BaseName, Location_) values ('722146', 'Lion''s Den', 'Dimona');
insert into Base (BaseID, BaseName, Location_) values ('092010', 'Shadow Ridge Base', 'Kiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('063195', 'Phoenix Stronghold', 'Yavne');
insert into Base (BaseID, BaseName, Location_) values ('822433', 'Shadow Ridge Base', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('562323', 'Wolfpack Camp', 'Haifa');
insert into Base (BaseID, BaseName, Location_) values ('053596', 'Wolfpack Camp', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('869536', 'Phoenix Stronghold', 'Ashdod');
insert into Base (BaseID, BaseName, Location_) values ('328612', 'Spartan Citadel', 'Nahariya');
insert into Base (BaseID, BaseName, Location_) values ('598313', 'Thunderstrike Outpost', 'Eilat');
insert into Base (BaseID, BaseName, Location_) values ('026714', 'Viper Valley Base', 'Qiryat Gat');
insert into Base (BaseID, BaseName, Location_) values ('939776', 'Spartan Citadel', 'Or Yehuda');
insert into Base (BaseID, BaseName, Location_) values ('969197', 'Spartan Citadel', 'Yavne');
commit;
